## Introdução ao NumPy


*NumPy* é particularmente útil para produzir soluções rápidas de processamento vetorial. 

Leitura inicial:
https://numpy.org/devdocs/user/quickstart.html

Leitura recomendada:
http://www.scipy-lectures.org/intro/numpy

Documentação de referência:
http://docs.scipy.org/


In [1]:
# Um exemplo
import numpy as np
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [2]:
b = np.array([[0,1, 2],
              [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
# dimensão da matriz
b.shape

(2, 3)

### Documentação

In [4]:
# Acesso à documentação 
help (np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [5]:
# Em alternativa
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (column major).
   

In [6]:
# ou ainda
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.lib.Arrayterator
    Buffered iterator for big arrays.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.ma.MaskedArray.__new__
    Create a 

In [7]:
# ou ainda
np.con*?


np.concatenate
np.conj
np.conjugate
np.convolve

### Alguns exemplos

In [8]:
# matriz com 1s
a = np.ones((3, 3)) 
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# matriz com 0s
b = np.zeros((2, 2))
b

array([[0., 0.],
       [0., 0.]])

In [10]:
# Matrix com 1 na diagonal e demais elementos a zero
c = np.eye(3, dtype=int) 
c

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
# Matrix com 1.0 na diagonal e demais elementos a zero
c = np.eye(3, dtype=float) 
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [13]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a[2:9:3] # [start:end:step]

array([2, 5, 8])

In [15]:
# Indexação dos elementos das matrizes
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [16]:
a[1, 1]

1

In [17]:
a[2, 1] = 10 # third line, second column

In [18]:
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [19]:
# a segunda linha
a[1]

array([0, 1, 0])

In [20]:
# a segunda coluna
a[:,1]

array([ 0,  1, 10])

### Operações elementares

In [21]:
a = np.array( 10 * np.arange(4) )
a

array([ 0, 10, 20, 30])

In [22]:
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [23]:
c = a-b
c

array([ 0,  9, 18, 27])

In [24]:
d = b**2
d

array([0, 1, 4, 9])

In [25]:
d1 = d + 5
d1

array([ 5,  6,  9, 14])

In [26]:
A = np.array( [[1,1],
            [0,1]] )
B = np.array( [[2,0],
            [3,4]] )

In [27]:
C = A * B                       # produto elemento a elemento
C

array([[2, 0],
       [0, 4]])

In [28]:
D = A @ B                       # produto de matrizes
D

array([[5, 4],
       [3, 4]])

In [29]:
A.dot(B)                    # outra forma de multiplicar matrizes

array([[5, 4],
       [3, 4]])

### Exercícios
Crie as matrizes abaixo (e atenção aos tipos de dados)

In [30]:

[[1, 1, 1, 1],
 [1, 1, 1, 1],
 [1, 1, 1, 2],
 [1, 6, 1, 1]]

[[0., 0., 0., 0., 0.],
 [2., 0., 0., 0., 0.],
 [0., 3., 0., 0., 0.],
 [0., 0., 4., 0., 0.],
 [0., 0., 0., 5., 0.],
 [0., 0., 0., 0., 6.]]


[[0.0, 0.0, 0.0, 0.0, 0.0],
 [2.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 3.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 4.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 5.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 6.0]]